### ISSUE TITLE
bug: TypeError: Cannot read properties of undefined (reading 'code')

### ISSUE THREAD

**Issue by touka-0** [wagmi-dev/references#332]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

We experienced some cryptic error reported by Sentry on production:

```
TypeError: Cannot read properties of undefined (reading 'code')
  at ig.<anonymous>(./node_modules/@wagmi/connectors/dist/chunk-FIR52KXR.js:165:1)
  at MF(app:///inpage.js:13:7359)
  at DE.emit(app:///inpage.js:13:7250)
  at ig.<anonymous>(app:///inpage.js:57:186389)
  at MF(app:///inpage.js:13:7359)
  at DE.emit(app:///inpage.js:13:7310)
  at DE.<anonymous>(app:///inpage.js:57:186783)
  at MF(app:///inpage.js:13:7359)
  at DE.emit(app:///inpage.js:13:7310)
  at u(app:///inpage.js:13:7980)
  at nc.a [as _write](app:///inpage.js:13:7780)
  at oE(app:///inpage.js:10:9380)
  at Phe(app:///inpage.js:10:9250)
  at Ei.write(app:///inpage.js:10:8049)
  at HE.I(app:///inpage.js:10:23460)
  at O0e(app:///inpage.js:1:58696)
  at Mn.emit(app:///inpage.js:1:61564)
  at gE(app:///inpage.js:10:20095)
  at xN(app:///inpage.js:10:19991)
  at jn.push(app:///inpage.js:10:19416)
  at qE._write(app:///inpage.js:13:8927)
  at oE(app:///inpage.js:10:9380)
  at Phe(app:///inpage.js:10:9250)
  at Ei.write(app:///inpage.js:10:8049)
  at Hv.I(app:///inpage.js:10:23460)
  at O0e(app:///inpage.js:1:58696)
  at Mn.emit(app:///inpage.js:1:61564)
  at gE(app:///inpage.js:10:20095)
  at xN(app:///inpage.js:10:19991)
  at jn.push(app:///inpage.js:10:19416)
  at Hv._onMessage(app:///inpage.js:10:31156)
```

Figured out it's rooted in some disconnect handling logic https://github.com/wagmi-dev/references/blob/4b016df3f4930f49f9bb995a580a2729d3828bf9/packages/connectors/src/injected.ts#L316

### Expected Behavior

No error occurred

### Steps To Reproduce

1. Open https://stackblitz.com/edit/new-wagmi and wait for ready
2. Connect your wallet via "Injected" button
3. Then (maybe) let your computer go to sleep (I closed the lid of my MacBook with all cables disconnected for more than 30 min.)
4. Reopen the computer, the following error can be seen in console:

```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'code')
    at FrameProvider.<anonymous> (chunk-ACKAHAMS.js?v=26c3fe09:157:17)
    at FrameProvider.emit (<anonymous>:1:11485)
    at Connection.<anonymous> (<anonymous>:1:1198)
    at Connection.emit (<anonymous>:1:11485)
    at <anonymous>:1:15141
```

### Link to Minimal Reproducible Example (CodeSandbox, StackBlitz, etc.)

https://stackblitz.com/edit/new-wagmi

### Anything else?

OS: macOS 13.4
Browser: Chromium 110.0.5481.100 (arm64)
Wallet: Frame v0.6.6

**Comment by tmm** [comment]
Thanks for reporting. This issue is temporarily closed due to lack of information. Please provide a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example) and reopen this issue.

**Comment by tmm** [comment]
@touka-0 that link doesn't work. mind dropping a valid one?

**Comment by jxom** [comment]
Seems like your wallet doesn't implement `disconnect` events correctly. They are meant to emit an error. We can fix this up to check if an error exists.

**Comment by tmm** [comment]
If this issue still exists in the current version of Wagmi, please create a new issue on the [Wagmi repo](https://github.com/wagmi-dev/wagmi). Connectors are moving over there.
